#!/usr/bin/env python
"""
Helper script to run Shopify tests locally with a mock MCP server.
This avoids BrowserStack dependencies while testing backend integration.
"""

import os
import sys
import subprocess
import argparse
from pathlib import Path

def main():
    parser = argparse.ArgumentParser(description='Run Shopify tests locally with mock MCP server')
    parser.add_argument('--feature', help='Specific feature file to run (relative to features directory)')
    parser.add_argument('--tag', help='Specific tag to run (e.g. shopify)', default='shopify')
    parser.add_argument('--real-mcp', action='store_true', help='Use real MCP server instead of mock')
    parser.add_argument('--verbose', '-v', action='store_true', help='Show verbose output')
    parser.add_argument('--no-color', action='store_true', help='Disable colored output')
    args = parser.parse_args()
    
    # Set environment variables for testing
    os.environ['USE_MOCK_MCP'] = 'false' if args.real_mcp else 'true'
    
    # Ensure Python path includes the project root and features directory
    project_root = Path(__file__).parent.absolute()
    features_dir = project_root / 'features'
    steps_dir = features_dir / 'steps'
    
    # Create a proper PYTHONPATH that includes all necessary directories
    pythonpath_parts = [
        str(project_root),  # Root directory
        str(features_dir),  # Features directory
        str(steps_dir),     # Steps directory
    ]
    
    # Add existing PYTHONPATH if it exists
    current_pythonpath = os.environ.get('PYTHONPATH', '')
    if current_pythonpath:
        pythonpath_parts.append(current_pythonpath)
    
    # Set the updated PYTHONPATH
    os.environ['PYTHONPATH'] = os.pathsep.join(pythonpath_parts)
    
    # Ensure steps directories have __init__.py files
    for directory in (features_dir, steps_dir):
        init_file = directory / '__init__.py'
        if not init_file.exists():
            with open(init_file, 'w') as f:
                f.write('# Auto-generated by run_local_tests.py\n')
    
    # Construct the behave command
    behave_cmd = [sys.executable, '-m', 'behave']
    
    # Add formatting options
    if args.no_color:
        behave_cmd.extend(['-f', 'plain'])
    else:
        behave_cmd.extend(['-f', 'pretty'])
    
    # Add tag if specified
    if args.tag:
        behave_cmd.extend(['--tags', args.tag])
    
    # Add verbose flag if specified
    if args.verbose:
        behave_cmd.append('-v')
    
    # Add specific feature file if specified
    if args.feature:
        feature_path = features_dir / args.feature
        if not feature_path.exists() and not str(args.feature).startswith('features/'):
            feature_path = features_dir / args.feature
        behave_cmd.append(str(feature_path))
    
    print(f"Using PYTHONPATH: {os.environ['PYTHONPATH']}")
    print(f"Running command: {' '.join(behave_cmd)}")
    
    # Run behave
    result = subprocess.run(behave_cmd, cwd=project_root)
    
    return result.returncode

if __name__ == '__main__':
    sys.exit(main())
